version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=DEV
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             (python manage.py createsuperuser --noinput || true) &&
             python manage.py runserver 0.0.0.0:8000"

